import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  BarChart3,
  Bell,
  CalendarDays,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  CreditCard,
  FileText,
  FlaskConical,
  History,
  LayoutGrid,
  PackageCheck,
  ReceiptText,
  ScanLine,
  ShieldAlert,
  Stethoscope,
  Users,
  WalletCards,
} from 'lucide-react';

export const reportsMenuSections = [
  {
    id: 'executive-overview',
    label: 'Tổng quan điều hành',
    icon: LayoutGrid,
    defaultOpen: true,
    children: [
      { id: 'overview-dashboard', label: 'Bảng điều khiển tổng quan', to: '/reports/dashboard', icon: LayoutGrid },
      { id: 'overview-today-metrics', label: 'Chỉ số hôm nay', to: '/reports/executive-overview/today-metrics', icon: BarChart3 },
      { id: 'overview-period-metrics', label: 'Chỉ số tuần / tháng', to: '/reports/executive-overview/week-month-metrics', icon: CalendarDays },
      { id: 'overview-previous-comparison', label: 'So sánh kỳ trước', to: '/reports/executive-overview/previous-period-comparison', icon: ArrowLeftRight },
      { id: 'overview-abnormal-alerts', label: 'Cảnh báo bất thường', to: '/reports/executive-overview/abnormal-alerts', icon: AlertTriangle },
      { id: 'overview-key-trends', label: 'Xu hướng chính', to: '/reports/executive-overview/key-trends', icon: Activity },
      { id: 'overview-attention-items', label: 'Việc cần chú ý', to: '/reports/executive-overview/attention-items', icon: ClipboardCheck },
    ],
  },
  {
    id: 'clinical-operations',
    label: 'Vận hành khám bệnh',
    icon: Activity,
    defaultOpen: true,
    children: [
      { id: 'operations-visits', label: 'Lượt khám và lượt điều trị', to: '/reports/clinical-operations/visits-encounters', icon: Stethoscope },
      { id: 'operations-appointments', label: 'Lịch hẹn', to: '/reports/clinical-operations/appointments', icon: CalendarDays },
      { id: 'operations-checkin', label: 'Tiếp nhận', to: '/reports/clinical-operations/check-in', icon: CheckCircle2 },
      { id: 'operations-queue', label: 'Hàng đợi', to: '/reports/clinical-operations/queue', icon: Users },
      { id: 'operations-no-show', label: 'Không đến khám', to: '/reports/clinical-operations/no-show', icon: AlertTriangle },
      { id: 'operations-waiting-time', label: 'Thời gian chờ', to: '/reports/clinical-operations/waiting-time', icon: Clock3 },
      { id: 'operations-department-load', label: 'Tải khoa / phòng', to: '/reports/clinical-operations/department-room-load', icon: Activity },
      { id: 'operations-slot-efficiency', label: 'Hiệu suất suất khám', to: '/reports/clinical-operations/slot-efficiency', icon: BarChart3 },
      { id: 'operations-patient-flow', label: 'Luồng bệnh nhân', to: '/reports/clinical-operations/patient-flow', icon: ArrowLeftRight },
    ],
  },
  {
    id: 'departments-doctors',
    label: 'Khoa và bác sĩ',
    icon: Users,
    defaultOpen: false,
    children: [
      { id: 'department-performance', label: 'Hiệu suất khoa', to: '/reports/departments-doctors/department-performance', icon: BarChart3 },
      { id: 'department-load', label: 'Tải khoa', to: '/reports/departments-doctors/department-load', icon: Activity },
      { id: 'department-appointments', label: 'Lịch hẹn theo khoa', to: '/reports/departments-doctors/department-appointments', icon: CalendarDays },
      { id: 'department-queue', label: 'Hàng đợi theo khoa', to: '/reports/departments-doctors/department-queue', icon: ClipboardList },
      { id: 'department-revenue', label: 'Doanh thu theo khoa', to: '/reports/departments-doctors/department-revenue', icon: WalletCards },
      { id: 'department-staff', label: 'Nhân sự theo khoa', to: '/reports/departments-doctors/department-staff', icon: Users },
      { id: 'doctor-performance', label: 'Hiệu suất bác sĩ', to: '/reports/departments-doctors/doctor-performance', icon: Stethoscope },
      { id: 'doctor-utilization', label: 'Mức sử dụng bác sĩ', to: '/reports/departments-doctors/doctor-utilization', icon: BarChart3 },
      { id: 'doctor-no-show', label: 'Không đến khám theo bác sĩ', to: '/reports/departments-doctors/doctor-no-show', icon: AlertTriangle },
      { id: 'doctor-follow-up', label: 'Tái khám', to: '/reports/departments-doctors/follow-up', icon: History },
      { id: 'doctor-personal-report', label: 'Báo cáo cá nhân', to: '/reports/departments-doctors/personal-report', icon: FileText },
    ],
  },
  {
    id: 'finance-billing',
    label: 'Tài chính / viện phí',
    icon: WalletCards,
    defaultOpen: true,
    children: [
      { id: 'finance-dashboard', label: 'Bảng điều khiển tài chính', to: '/reports/finance-billing/dashboard', icon: LayoutGrid },
      { id: 'finance-revenue', label: 'Doanh thu', to: '/reports/finance-billing/revenue', icon: BarChart3 },
      { id: 'finance-debt', label: 'Công nợ', to: '/reports/finance-billing/debt', icon: WalletCards },
      { id: 'finance-debt-aging', label: 'Tuổi nợ công nợ', to: '/reports/finance-billing/debt-aging', icon: Clock3 },
      { id: 'finance-invoices', label: 'Hóa đơn', to: '/reports/finance-billing/invoices', icon: ReceiptText },
      { id: 'finance-payments', label: 'Thanh toán', to: '/reports/finance-billing/payments', icon: CreditCard },
      { id: 'finance-payment-method', label: 'Theo phương thức thanh toán', to: '/reports/finance-billing/payment-method', icon: CreditCard },
      { id: 'finance-refund-void', label: 'Hoàn tiền / hủy', to: '/reports/finance-billing/refund-void', icon: ArrowLeftRight },
      { id: 'finance-reconciliation', label: 'Đối soát', to: '/reports/finance-billing/reconciliation', icon: ClipboardCheck },
      { id: 'finance-insurance', label: 'Bảo hiểm', to: '/reports/finance-billing/insurance', icon: ShieldAlert },
    ],
  },
  {
    id: 'clinical-services',
    label: 'Cận lâm sàng và thủ thuật',
    icon: FlaskConical,
    defaultOpen: false,
    children: [
      { id: 'clinical-overview', label: 'Tổng quan cận lâm sàng', to: '/reports/clinical-services/overview', icon: LayoutGrid },
      { id: 'clinical-lab-orders', label: 'Chỉ định xét nghiệm', to: '/reports/clinical-services/lab-orders', icon: FlaskConical },
      { id: 'clinical-lab-turnaround', label: 'Thời gian trả kết quả xét nghiệm', to: '/reports/clinical-services/lab-turnaround-time', icon: Clock3 },
      { id: 'clinical-specimen-report', label: 'Báo cáo mẫu bệnh phẩm', to: '/reports/clinical-services/specimen-report', icon: ClipboardList },
      { id: 'clinical-imaging-orders', label: 'Chỉ định chẩn đoán hình ảnh', to: '/reports/clinical-services/imaging-orders', icon: ScanLine },
      { id: 'clinical-imaging-turnaround', label: 'Thời gian trả kết quả chẩn đoán hình ảnh', to: '/reports/clinical-services/imaging-turnaround-time', icon: Clock3 },
      { id: 'clinical-report-pending', label: 'Báo cáo chờ xử lý', to: '/reports/clinical-services/report-pending', icon: ClipboardCheck },
      { id: 'clinical-critical-results', label: 'Kết quả nguy cấp', to: '/reports/clinical-services/critical-results', icon: ShieldAlert },
      { id: 'clinical-procedure-orders', label: 'Chỉ định thủ thuật', to: '/reports/clinical-services/procedure-orders', icon: ClipboardList },
      { id: 'clinical-overdue-orders', label: 'Chỉ định quá hạn', to: '/reports/clinical-services/overdue-orders', icon: AlertTriangle },
    ],
  },
  {
    id: 'pharmacy-inventory',
    label: 'Nhà thuốc và kho dược',
    icon: PackageCheck,
    defaultOpen: false,
    children: [
      { id: 'pharmacy-dashboard', label: 'Bảng điều khiển kho dược', to: '/reports/pharmacy-inventory/dashboard', icon: LayoutGrid },
      { id: 'pharmacy-stock', label: 'Tồn kho', to: '/reports/pharmacy-inventory/stock', icon: PackageCheck },
      { id: 'pharmacy-stock-movement', label: 'Nhập xuất tồn', to: '/reports/pharmacy-inventory/stock-movement', icon: ArrowLeftRight },
      { id: 'pharmacy-low-stock', label: 'Sắp hết thuốc', to: '/reports/pharmacy-inventory/low-stock', icon: AlertTriangle },
      { id: 'pharmacy-expiring-batches', label: 'Lô sắp hết hạn', to: '/reports/pharmacy-inventory/expiring-batches', icon: Clock3 },
      { id: 'pharmacy-expired-recalled', label: 'Lô hết hạn / đã thu hồi', to: '/reports/pharmacy-inventory/expired-recalled-batches', icon: ShieldAlert },
      { id: 'pharmacy-dispensing', label: 'Cấp phát thuốc', to: '/reports/pharmacy-inventory/dispensing', icon: PackageCheck },
      { id: 'pharmacy-prescriptions', label: 'Đơn thuốc', to: '/reports/pharmacy-inventory/prescriptions', icon: ClipboardList },
      { id: 'pharmacy-stock-value', label: 'Giá trị tồn kho', to: '/reports/pharmacy-inventory/stock-value', icon: WalletCards },
      { id: 'pharmacy-stock-turnover', label: 'Vòng quay tồn kho', to: '/reports/pharmacy-inventory/stock-turnover', icon: Activity },
    ],
  },
  {
    id: 'inpatient-emergency',
    label: 'Nội trú và cấp cứu',
    icon: ShieldAlert,
    defaultOpen: false,
    children: [
      { id: 'inpatient-admission', label: 'Nhập viện', to: '/reports/inpatient-emergency/admissions', icon: ClipboardList },
      { id: 'inpatient-discharge', label: 'Xuất viện', to: '/reports/inpatient-emergency/discharge', icon: CheckCircle2 },
      { id: 'inpatient-bed-occupancy', label: 'Công suất giường', to: '/reports/inpatient-emergency/bed-occupancy', icon: Activity },
      { id: 'inpatient-bed-turnover', label: 'Vòng quay giường', to: '/reports/inpatient-emergency/bed-turnover', icon: ArrowLeftRight },
      { id: 'inpatient-length-of-stay', label: 'Thời gian nằm viện', to: '/reports/inpatient-emergency/length-of-stay', icon: Clock3 },
      { id: 'inpatient-tasks', label: 'Nhiệm vụ nội trú', to: '/reports/inpatient-emergency/inpatient-tasks', icon: ClipboardCheck },
      { id: 'emergency-cases', label: 'Ca cấp cứu', to: '/reports/inpatient-emergency/emergency-cases', icon: ShieldAlert },
      { id: 'emergency-response-time', label: 'Thời gian phản ứng', to: '/reports/inpatient-emergency/response-time', icon: Clock3 },
      { id: 'emergency-case-resolution', label: 'Kết quả xử lý ca', to: '/reports/inpatient-emergency/case-resolution', icon: CheckCircle2 },
    ],
  },
  {
    id: 'quality-risk',
    label: 'Chất lượng / rủi ro',
    icon: ShieldAlert,
    defaultOpen: false,
    children: [
      { id: 'quality-dashboard', label: 'Bảng điều khiển chất lượng', to: '/reports/quality-risk/dashboard', icon: LayoutGrid },
      { id: 'quality-critical-alerts', label: 'Cảnh báo nguy cấp', to: '/reports/quality-risk/critical-alerts', icon: AlertTriangle },
      { id: 'quality-break-glass', label: 'Báo cáo truy cập khẩn cấp', to: '/reports/quality-risk/break-glass-report', icon: ShieldAlert },
      { id: 'quality-audit-sensitive', label: 'Kiểm toán truy cập nhạy cảm', to: '/reports/quality-risk/audit-sensitive-access', icon: ClipboardCheck },
      { id: 'quality-login-security', label: 'Kiểm toán đăng nhập và bảo mật', to: '/reports/quality-risk/login-security-audit', icon: ShieldAlert },
      { id: 'quality-support-tickets', label: 'Phiếu hỗ trợ', to: '/reports/quality-risk/support-tickets', icon: ClipboardList },
      { id: 'quality-complaint-rating', label: 'Khiếu nại / đánh giá', to: '/reports/quality-risk/complaint-rating', icon: Bell },
      { id: 'quality-service-commitment', label: 'Cam kết mức dịch vụ', to: '/reports/quality-risk/service-commitment', icon: Clock3 },
      { id: 'quality-job-failure', label: 'Lỗi tác vụ nền', to: '/reports/quality-risk/job-failure', icon: AlertTriangle },
      { id: 'quality-notification-delivery', label: 'Gửi thông báo', to: '/reports/quality-risk/notification-delivery', icon: Bell },
    ],
  },
  {
    id: 'medical-records',
    label: 'Hồ sơ và tài liệu',
    icon: FileText,
    defaultOpen: false,
    children: [
      { id: 'records-medical', label: 'Hồ sơ bệnh án', to: '/reports/medical-records/records', icon: FileText },
      { id: 'records-finalized', label: 'Hồ sơ đã hoàn tất', to: '/reports/medical-records/finalized', icon: CheckCircle2 },
      { id: 'records-released', label: 'Hồ sơ đã phát hành', to: '/reports/medical-records/released', icon: FileText },
      { id: 'records-archived', label: 'Hồ sơ đã hủy / lưu trữ', to: '/reports/medical-records/void-archive', icon: AlertTriangle },
      { id: 'records-attachment-report', label: 'Báo cáo tệp đính kèm', to: '/reports/medical-records/attachment-report', icon: ClipboardList },
      { id: 'records-export', label: 'Xuất hồ sơ', to: '/reports/medical-records/export', icon: FileText },
      { id: 'records-document-timeline', label: 'Dòng thời gian tài liệu', to: '/reports/medical-records/document-timeline', icon: History },
    ],
  },
  {
    id: 'custom-reports',
    label: 'Báo cáo tùy chỉnh',
    icon: BarChart3,
    defaultOpen: false,
    children: [
      { id: 'custom-builder', label: 'Trình tạo báo cáo', to: '/reports/custom/builder', icon: ClipboardCheck },
      { id: 'custom-dataset', label: 'Tập dữ liệu', to: '/reports/custom/dataset', icon: ClipboardList },
      { id: 'custom-filters', label: 'Bộ lọc', to: '/reports/custom/filters', icon: ClipboardList },
      { id: 'custom-columns', label: 'Cột hiển thị', to: '/reports/custom/display-columns', icon: FileText },
      { id: 'custom-charts', label: 'Biểu đồ', to: '/reports/custom/charts', icon: BarChart3 },
      { id: 'custom-my-reports', label: 'Báo cáo của tôi', to: '/reports/custom/my-reports', icon: FileText },
      { id: 'custom-shared-reports', label: 'Báo cáo dùng chung', to: '/reports/custom/shared-reports', icon: Users },
      { id: 'custom-pinned-reports', label: 'Báo cáo được ghim', to: '/reports/custom/pinned-reports', icon: CheckCircle2 },
    ],
  },
  {
    id: 'exports',
    label: 'Xuất báo cáo',
    icon: FileText,
    defaultOpen: false,
    children: [
      { id: 'export-csv', label: 'Xuất tệp CSV', to: '/reports/exports/csv', icon: FileText },
      { id: 'export-excel', label: 'Xuất tệp Excel', to: '/reports/exports/excel', icon: FileText },
      { id: 'export-pdf', label: 'Xuất tệp PDF', to: '/reports/exports/pdf', icon: FileText },
      { id: 'export-history', label: 'Lịch sử xuất báo cáo', to: '/reports/exports/history', icon: History },
      { id: 'export-processing', label: 'Xuất báo cáo đang xử lý', to: '/reports/exports/processing', icon: Clock3 },
      { id: 'export-failed', label: 'Xuất báo cáo thất bại', to: '/reports/exports/failed', icon: AlertTriangle },
      { id: 'export-schedules', label: 'Lịch gửi định kỳ', to: '/reports/exports/schedules', icon: CalendarDays },
      { id: 'saved-reports', label: 'Báo cáo đã lưu', to: '/reports/exports/saved-reports', icon: FileText },
    ],
  },
];

export function flattenReportsMenu(sections = reportsMenuSections) {
  return sections.flatMap((section) =>
    (section.children || []).map((item) => ({
      ...item,
      sectionId: section.id,
      sectionLabel: section.label,
    })),
  );
}

export function getReportsPageMeta(pathname = '/reports/dashboard') {
  const normalizedPath = pathname === '/reports' ? '/reports/dashboard' : pathname;
  const item = flattenReportsMenu().find((entry) => entry.to === normalizedPath);

  return item || {
    id: 'overview-dashboard',
    label: 'Bảng điều khiển tổng quan',
    sectionLabel: 'Tổng quan điều hành',
    to: '/reports/dashboard',
    icon: LayoutGrid,
  };
}
