const express = require('express');
const ApiResponse = require('../common/responses/api-response');
const accessAuthorizationRoutes = require('./access-authorization.routes');
const appointmentRoutes = require('./appointment.routes');
const adminRoutes = require('./admin.routes');
const auditRoutes = require('./audit.routes');
const authRoutes = require('./auth.routes');
const billingRoutes = require('./billing.routes');
const clinicalAlertRoutes = require('./clinical-alert.routes');
const clinicalConfigRoutes = require('./clinical-config.routes');
const clinicalDocumentFilesRoutes = require('./clinical-document-files.routes');
const clinicalInvestigationRoutes = require('./clinical-investigation.routes');
const clinicalOrderCenterRoutes = require('./clinical-order-center.routes');
const clinicalOperationsOverviewRoutes = require('./clinical-operations-overview.routes');
const clinicalResultReviewRoutes = require('./clinical-result-review.routes');
const clinicalRoutes = require('./clinical.routes');
const dashboardRoutes = require('./dashboard.routes');
const departmentRoutes = require('./department.routes');
const diagnosticAlertRoutes = require('./diagnostic-alert.routes');
const devBankQrRoutes = require('./dev-bank-qr.routes');
const directoryRoutes = require('./directory.routes');
const doctorProfileRoutes = require('./doctor-profile.routes');
const emergencyRoutes = require('./emergency.routes');
const encounterRoutes = require('./encounter.routes');
const iamRoutes = require('./iam.routes');
const imagingRoutes = require('./imaging.routes');
const inpatientRoutes = require('./inpatient.routes');
const laboratoryRoutes = require('./laboratory.routes');
const messageRoutes = require('./message.routes');
const medicationAdministrationRoutes = require('./medication-administration.routes');
const notificationRoutes = require('./notification.routes');
const nursingRoutes = require('./nursing.routes');
const orderRoutes = require('./order.routes');
const paymentsRoutes = require('./payments.routes');
const patientRoutes = require('./patient.routes');
const pharmacyConfigRoutes = require('./pharmacy-config.routes');
const pharmacyOverviewRoutes = require('./pharmacy-overview.routes');
const portalRoutes = require('./portal.routes');
const procedureRoutes = require('./procedure.routes');
const prescriptionRoutes = require('./prescription.routes');
const queueRoutes = require('./queue.routes');
const qrTokenRoutes = require('./qr-token.routes');
const reportsRoutes = require('./reports.routes');
const recordsRoutes = require('./records.routes');
const scheduleRoutes = require('./schedule.routes');
const staffRoutes = require('./staff.routes');
const supportTicketRoutes = require('./support-ticket.routes');
const userPreferenceRoutes = require('./user-preference.routes');

const router = express.Router();

router.get('/health', (req, res) => {
  return ApiResponse.success(res, {
    ok: true,
    service: 'healthcare-system-backend',
  }, 'Service healthy.');
});

router.use('/auth', authRoutes);
router.use('/admin', adminRoutes);
router.use('/access', accessAuthorizationRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/billing', billingRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/iam', iamRoutes);
router.use('/staff', staffRoutes);
router.use('/departments', departmentRoutes);
router.use('/diagnostics/alerts', diagnosticAlertRoutes);
router.use('/dev/bank-qr', devBankQrRoutes);
router.use('/directory', directoryRoutes);
router.use('/doctor-profiles', doctorProfileRoutes);
router.use('/emergency', emergencyRoutes);
router.use('/patients', patientRoutes);
router.use('/portal', portalRoutes);
router.use('/schedules', scheduleRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/queue', queueRoutes);
router.use('/qr', qrTokenRoutes);
router.use('/reports', reportsRoutes);
router.use('/encounters', encounterRoutes);
router.use('/clinical', clinicalRoutes);
router.use('/clinical-alerts', clinicalAlertRoutes);
router.use('/clinical-config', clinicalConfigRoutes);
router.use('/clinical-document-files', clinicalDocumentFilesRoutes);
router.use('/clinical-investigation', clinicalInvestigationRoutes);
router.use('/clinical-order-center', clinicalOrderCenterRoutes);
router.use('/clinical-operations', clinicalOperationsOverviewRoutes);
router.use('/clinical-results/review', clinicalResultReviewRoutes);
router.use('/imaging', imagingRoutes);
router.use('/inpatient', inpatientRoutes);
router.use('/lab', laboratoryRoutes);
router.use('/laboratory', laboratoryRoutes);
router.use('/medication-administrations', medicationAdministrationRoutes);
router.use('/notifications', notificationRoutes);
router.use('/nursing', nursingRoutes);
router.use('/messages', messageRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentsRoutes);
router.use('/pharmacy-config', pharmacyConfigRoutes);
router.use('/pharmacy', pharmacyOverviewRoutes);
router.use('/procedures', procedureRoutes);
router.use('/prescriptions', prescriptionRoutes);
router.use('/records', recordsRoutes);
router.use('/support', supportTicketRoutes);
router.use('/preferences', userPreferenceRoutes);

module.exports = router;
