const errorMiddlewareModule = require('./middlewares/error.middleware');

module.exports = {
  ApiError: require('./errors/api-error'),
  ERROR_CODE: require('./errors/error-codes'),
  errorFactory: require('./errors/error-factory'),
  ApiResponse: require('./responses/api-response'),
  RESPONSE_MESSAGE: require('./responses/response-messages'),
  controllers: require('./controllers'),
  asyncHandler: require('./middlewares/async-handler'),
  errorMiddleware: errorMiddlewareModule.errorMiddleware,
  normalizeError: errorMiddlewareModule.normalizeError,
  validate: require('./middlewares/validate.middleware'),
  requestContextMiddleware: require('./middlewares/request-context.middleware'),
  notFoundMiddleware: require('./middlewares/not-found.middleware'),
  objectIdHelper: require('./helpers/object-id.helper'),
  dateTimeHelper: require('./helpers/date-time.helper'),
  paginationHelper: require('./helpers/pagination.helper'),
  queryHelper: require('./helpers/query.helper'),
  softDeleteHelper: require('./helpers/soft-delete.helper'),
  moneyHelper: require('./helpers/money.helper'),
  stringHelper: require('./helpers/string.helper'),
  auth: require('./auth'),
  actors: require('./actors'),
  permissionChecker: require('./permissions'),
  scopeChecker: require('./scopes'),
  auditContext: require('./audit'),
  validators: require('./validators'),
};
