const PERMISSION_MODULE = {
  SYSTEM: 'system',
  OPERATIONS: 'operations',
  INTEGRATIONS: 'integrations',
  PATIENT_PORTAL: 'patient_portal',
  SUPPORT_COMMUNICATION: 'support_communication',
  ADMIN_TOOLS: 'admin_tools',
  SETTINGS: 'settings',
  USERS: 'users',
  ROLES: 'roles',
  PERMISSIONS: 'permissions',
  DEPARTMENTS: 'departments',
  DOCTOR_PROFILES: 'doctor_profiles',
  PATIENTS: 'patients',
  PATIENT_IDENTIFIERS: 'patient_identifiers',
  PATIENT_ACCOUNTS: 'patient_accounts',
  PATIENT_RELATIVES: 'patient_relatives',
  PATIENT_AUTHORIZATIONS: 'patient_authorizations',
  SCHEDULES: 'schedules',
  SCHEDULE_SLOTS: 'schedule_slots',
  APPOINTMENTS: 'appointments',
  QUEUE: 'queue',
  ENCOUNTERS: 'encounters',
  CONSULTATIONS: 'consultations',
  DIAGNOSES: 'diagnoses',
  PROBLEMS: 'problems',
  ALLERGIES: 'allergies',
  VITAL_SIGNS: 'vital_signs',
  CLINICAL_NOTES: 'clinical_notes',
  CARE_PLANS: 'care_plans',
  ORDERS: 'orders',
  LAB_ORDERS: 'lab_orders',
  SPECIMENS: 'specimens',
  LAB_RESULTS: 'lab_results',
  IMAGING_ORDERS: 'imaging_orders',
  IMAGING_REPORTS: 'imaging_reports',
  PROCEDURE_ORDERS: 'procedure_orders',
  DIAGNOSTIC_ALERTS: 'diagnostic_alerts',
  LAB_TEST_CATALOG: 'lab_test_catalog',
  SPECIMEN_TYPE_CATALOG: 'specimen_type_catalog',
  IMAGING_MODALITY_CATALOG: 'imaging_modality_catalog',
  IMAGING_EQUIPMENT: 'imaging_equipment',
  PROCEDURE_CATALOG: 'procedure_catalog',
  CLINICAL_SLA_RULES: 'clinical_sla_rules',
  RESULT_REPORT_TEMPLATES: 'result_report_templates',
  MEDICATIONS: 'medications',
  PRESCRIPTIONS: 'prescriptions',
  DISPENSES: 'dispenses',
  MEDICATION_ADMINISTRATIONS: 'medication_administrations',
  WARD_BOARD: 'ward_board',
  BED_SUGGESTIONS: 'bed_suggestions',
  DISCHARGE_READINESS: 'discharge_readiness',
  INPATIENT_TASKS: 'inpatient_tasks',
  INPATIENT_HANDOVERS: 'inpatient_handovers',
  STOCK_BATCHES: 'stock_batches',
  INVENTORY_TRANSACTIONS: 'inventory_transactions',
  ROOMS: 'rooms',
  BEDS: 'beds',
  ADMISSIONS: 'admissions',
  BED_ASSIGNMENTS: 'bed_assignments',
  SERVICE_CATALOG: 'service_catalog',
  CHARGES: 'charges',
  INVOICES: 'invoices',
  PAYMENTS: 'payments',
  PAYMENT_RECONCILIATION: 'payment_reconciliation',
  RECEIPTS: 'receipts',
  INSURANCE_POLICIES: 'insurance_policies',
  INSURANCE_CLAIMS: 'insurance_claims',
  MEDICAL_RECORDS: 'medical_records',
  ATTACHMENTS: 'attachments',
  NOTIFICATIONS: 'notifications',
  AUDIT_LOGS: 'audit_logs',
  REPORTS: 'reports',
};

const LEGACY_PERMISSION_MODULE = {
  AUTH: 'auth',
  ROLE: 'role',
  PERMISSION: 'permission',
  SCHEDULE: 'schedule',
  VITALS: 'vitals',
};

const PERMISSION_MODULES = Object.values(PERMISSION_MODULE);

module.exports = {
  PERMISSION_MODULE,
  PERMISSION_MODULES,
  LEGACY_PERMISSION_MODULE,
};
