const PERMISSION = {
  SYSTEM: {
    FULL_ACCESS: 'system.full_access',
    HEALTH_READ: 'system.health.read',
  },
  COMMAND_CENTER: {
    READ: 'command_center.read',
    MANAGE: 'command_center.manage',
    EXPORT: 'command_center.export',
    VIEW_SECURITY: 'command_center.view_security',
    VIEW_OPS: 'command_center.view_ops',
    RETRY_OPS: 'command_center.retry_ops',
    MANAGE_ALERTS: 'command_center.manage_alerts',
    FORCE_LOGOUT: 'command_center.force_logout',
    MAINTENANCE: 'command_center.maintenance',
    VIEW_WORKSPACE_MAP: 'command_center.view_workspace_map',
  },
  SETTINGS: {
    READ: 'settings.read',
    READ_PUBLIC: 'settings.public.read',
    CREATE: 'settings.create',
    UPDATE: 'settings.update',
    UPDATE_SENSITIVE: 'settings.update_sensitive',
  },
  USERS: {
    READ: 'users.read',
    READ_LIMITED: 'users.read_limited',
    READ_DEPARTMENT: 'users.read_department',
    CREATE: 'users.create',
    UPDATE: 'users.update',
    UPDATE_STATUS: 'users.update_status',
    DELETE: 'users.delete',
    LOCK: 'users.lock',
    UNLOCK: 'users.unlock',
    RESET_PASSWORD: 'users.reset_password',
    FORCE_LOGOUT: 'users.force_logout',
    TRANSFER_DEPARTMENT: 'users.transfer_department',
    ASSIGN_ROLES: 'users.assign_roles',
    REMOVE_ROLES: 'users.remove_roles',
  },
  ROLES: {
    READ: 'roles.read',
    CREATE: 'roles.create',
    UPDATE: 'roles.update',
    DELETE: 'roles.delete',
    ASSIGN_PERMISSIONS: 'roles.assign_permissions',
  },
  PERMISSIONS: {
    READ: 'permissions.read',
    CREATE: 'permissions.create',
    UPDATE: 'permissions.update',
    DELETE: 'permissions.delete',
  },
  DEPARTMENTS: {
    READ: 'departments.read',
    READ_OWN: 'departments.read_own',
    CREATE: 'departments.create',
    UPDATE: 'departments.update',
    UPDATE_STATUS: 'departments.update_status',
    DELETE: 'departments.delete',
    ASSIGN_HEAD: 'departments.assign_head',
    STAFF_READ: 'departments.staff.read',
  },
  DOCTOR_PROFILES: {
    READ: 'doctor_profiles.read',
    READ_OWN: 'doctor_profiles.read_own',
    READ_DEPARTMENT: 'doctor_profiles.read_department',
    PUBLIC_READ: 'doctor_profiles.public.read',
    CREATE: 'doctor_profiles.create',
    UPDATE: 'doctor_profiles.update',
    UPDATE_STATUS: 'doctor_profiles.update_status',
    DELETE: 'doctor_profiles.delete',
  },
  PATIENTS: {
    READ: 'patients.read',
    READ_LIMITED: 'patients.read_limited',
    READ_ASSIGNED: 'patients.read_assigned',
    SEARCH: 'patients.search',
    CREATE: 'patients.create',
    UPDATE: 'patients.update',
    UPDATE_BASIC: 'patients.update_basic',
    UPDATE_SENSITIVE: 'patients.update_sensitive',
    DELETE: 'patients.delete',
    ARCHIVE: 'patients.archive',
    MERGE: 'patients.merge',
    SELF_READ: 'patients.self.read',
    SELF_UPDATE_BASIC: 'patients.self.update_basic',
  },
  PATIENT_IDENTIFIERS: {
    READ: 'patient_identifiers.read',
    CREATE: 'patient_identifiers.create',
    UPDATE: 'patient_identifiers.update',
    DELETE: 'patient_identifiers.delete',
    MANAGE: 'patient_identifiers.manage',
  },
  PATIENT_ACCOUNTS: {
    READ: 'patient_accounts.read',
    CREATE: 'patient_accounts.create',
    UPDATE: 'patient_accounts.update',
    LOCK: 'patient_accounts.lock',
    UNLOCK: 'patient_accounts.unlock',
    RESET_PASSWORD: 'patient_accounts.reset_password',
  },
  PATIENT_RELATIVES: {
    READ: 'patient_relatives.read',
    CREATE: 'patient_relatives.create',
    UPDATE: 'patient_relatives.update',
    DELETE: 'patient_relatives.delete',
    LINKED_PATIENTS_READ: 'patient_relatives.linked_patients.read',
  },
  PATIENT_AUTHORIZATIONS: {
    READ: 'patient_authorizations.read',
    CREATE: 'patient_authorizations.create',
    APPROVE: 'patient_authorizations.approve',
    REVOKE: 'patient_authorizations.revoke',
    REJECT: 'patient_authorizations.reject',
    MANAGE: 'patient_authorizations.manage',
  },
  SCHEDULES: {
    READ: 'schedules.read',
    READ_OWN: 'schedules.read_own',
    READ_DEPARTMENT: 'schedules.read_department',
    PUBLIC_READ: 'schedules.public.read',
    CREATE: 'schedules.create',
    UPDATE: 'schedules.update',
    PUBLISH: 'schedules.publish',
    APPROVE_DEPARTMENT: 'schedules.approve_department',
    CANCEL: 'schedules.cancel',
    COMPLETE: 'schedules.complete',
    DUPLICATE: 'schedules.duplicate',
    BULK_CREATE: 'schedules.bulk_create',
    BULK_PUBLISH: 'schedules.bulk_publish',
  },
  SCHEDULE_SLOTS: {
    READ: 'schedule_slots.read',
    GENERATE: 'schedule_slots.generate',
    HOLD: 'schedule_slots.hold',
    BOOK: 'schedule_slots.book',
    BLOCK: 'schedule_slots.block',
    REOPEN: 'schedule_slots.reopen',
    BATCH_BLOCK: 'schedule_slots.batch_block',
    BATCH_REOPEN: 'schedule_slots.batch_reopen',
  },
  APPOINTMENTS: {
    READ: 'appointments.read',
    READ_OWN: 'appointments.read_own',
    READ_DEPARTMENT: 'appointments.read_department',
    SELF_READ: 'appointments.self.read',
    CREATE: 'appointments.create',
    SELF_CREATE: 'appointments.self.create',
    UPDATE: 'appointments.update',
    UPDATE_BASIC: 'appointments.update_basic',
    CONFIRM: 'appointments.confirm',
    CANCEL: 'appointments.cancel',
    CANCEL_BY_POLICY: 'appointments.cancel_by_policy',
    SELF_CANCEL_BY_POLICY: 'appointments.self.cancel_by_policy',
    RESCHEDULE: 'appointments.reschedule',
    RESCHEDULE_BY_POLICY: 'appointments.reschedule_by_policy',
    SELF_RESCHEDULE_BY_POLICY: 'appointments.self.reschedule_by_policy',
    CHECKIN: 'appointments.checkin',
    COMPLETE: 'appointments.complete',
    NO_SHOW: 'appointments.no_show',
  },
  QUEUE: {
    READ: 'queue.read',
    READ_OWN: 'queue.read_own',
    READ_DEPARTMENT: 'queue.read_department',
    SELF_READ: 'queue.self.read',
    CREATE: 'queue.create',
    UPDATE: 'queue.update',
    CALL: 'queue.call',
    CALL_OWN: 'queue.call_own',
    SKIP: 'queue.skip',
    RECALL: 'queue.recall',
    START_SERVICE: 'queue.start_service',
    START_SERVICE_OWN: 'queue.start_service_own',
    COMPLETE: 'queue.complete',
    CANCEL: 'queue.cancel',
    PRINT_TICKET: 'queue.print_ticket',
  },
  ENCOUNTERS: {
    READ: 'encounters.read',
    READ_OWN: 'encounters.read_own',
    READ_ASSIGNED: 'encounters.read_assigned',
    READ_DEPARTMENT: 'encounters.read_department',
    READ_BASIC: 'encounters.read_basic',
    READ_SUMMARY: 'encounters.read_summary',
    SELF_READ_SUMMARY: 'encounters.self.read_summary',
    READ_BILLING: 'encounters.read_billing',
    READ_MEDICAL_RECORD: 'encounters.read_medical_record',
    CREATE: 'encounters.create',
    CREATE_FROM_CHECKIN: 'encounters.create_from_checkin',
    START: 'encounters.start',
    UPDATE: 'encounters.update',
    UPDATE_OWN: 'encounters.update_own',
    UPDATE_NURSING_STATUS: 'encounters.update_nursing_status',
    COMPLETE: 'encounters.complete',
    COMPLETE_OWN: 'encounters.complete_own',
    CANCEL: 'encounters.cancel',
    CANCEL_OWN: 'encounters.cancel_own',
  },
  CONSULTATIONS: {
    READ: 'consultations.read',
    READ_OWN: 'consultations.read_own',
    READ_DEPARTMENT: 'consultations.read_department',
    READ_SIGNED: 'consultations.read_signed',
    SELF_READ_SIGNED: 'consultations.self.read_signed',
    CREATE: 'consultations.create',
    UPDATE: 'consultations.update',
    UPDATE_OWN: 'consultations.update_own',
    SIGN: 'consultations.sign',
    SIGN_OWN: 'consultations.sign_own',
    AMEND: 'consultations.amend',
    AMEND_OWN: 'consultations.amend_own',
    CANCEL: 'consultations.cancel',
  },
  DIAGNOSES: {
    READ: 'diagnoses.read',
    SELF_READ_RELEASED: 'diagnoses.self.read_released',
    CREATE: 'diagnoses.create',
    UPDATE: 'diagnoses.update',
    UPDATE_OWN: 'diagnoses.update_own',
    SET_PRIMARY: 'diagnoses.set_primary',
    ENTERED_IN_ERROR: 'diagnoses.entered_in_error',
    MANAGE: 'diagnoses.manage',
  },
  VITAL_SIGNS: {
    READ: 'vital_signs.read',
    CREATE: 'vital_signs.create',
    UPDATE_OWN: 'vital_signs.update_own',
    ENTERED_IN_ERROR: 'vital_signs.entered_in_error',
  },
  CLINICAL_NOTES: {
    READ: 'clinical_notes.read',
    READ_SIGNED: 'clinical_notes.read_signed',
    CREATE: 'clinical_notes.create',
    CREATE_NURSING: 'clinical_notes.create_nursing',
    UPDATE_OWN: 'clinical_notes.update_own',
    WRITE: 'clinical_notes.write',
    SIGN: 'clinical_notes.sign',
    AMEND: 'clinical_notes.amend',
  },
  PROBLEMS: {
    READ: 'problems.read',
    CREATE: 'problems.create',
    UPDATE: 'problems.update',
    RESOLVE: 'problems.resolve',
  },
  ALLERGIES: {
    READ: 'allergies.read',
    CREATE: 'allergies.create',
    UPDATE: 'allergies.update',
    RESOLVE: 'allergies.resolve',
  },
  CARE_PLANS: {
    READ: 'care_plans.read',
    CREATE: 'care_plans.create',
    UPDATE: 'care_plans.update',
    UPDATE_OWN: 'care_plans.update_own',
    COMPLETE_TASK: 'care_plans.complete_task',
    MANAGE: 'care_plans.manage',
  },
  NURSING_TASKS: {
    READ: 'nursing_tasks.read',
    READ_OWN: 'nursing_tasks.read_own',
    READ_DEPARTMENT: 'nursing_tasks.read_department',
    CREATE: 'nursing_tasks.create',
    ASSIGN: 'nursing_tasks.assign',
    ACCEPT: 'nursing_tasks.accept',
    START: 'nursing_tasks.start',
    COMPLETE: 'nursing_tasks.complete',
    COMPLETE_OWN: 'nursing_tasks.complete_own',
    REASSIGN: 'nursing_tasks.reassign',
    ESCALATE: 'nursing_tasks.escalate',
    CANCEL: 'nursing_tasks.cancel',
    REVIEW: 'nursing_tasks.review',
    MANAGE: 'nursing_tasks.manage',
  },
  NURSING_HANDOFFS: {
    READ: 'nursing_handoffs.read',
    READ_OWN: 'nursing_handoffs.read_own',
    READ_DEPARTMENT: 'nursing_handoffs.read_department',
    CREATE: 'nursing_handoffs.create',
    UPDATE_OWN: 'nursing_handoffs.update_own',
    SUBMIT: 'nursing_handoffs.submit',
    ACCEPT: 'nursing_handoffs.accept',
    REJECT: 'nursing_handoffs.reject',
    REOPEN: 'nursing_handoffs.reopen',
    EXPORT: 'nursing_handoffs.export',
    MANAGE: 'nursing_handoffs.manage',
  },
  ORDERS: {
    READ: 'orders.read',
    READ_OWN: 'orders.read_own',
    READ_DEPARTMENT: 'orders.read_department',
    READ_LAB: 'orders.read_lab',
    READ_IMAGING: 'orders.read_imaging',
    READ_PROCEDURE: 'orders.read_procedure',
    READ_MEDICATION: 'orders.read_medication',
    READ_SERVICE: 'orders.read_service',
    SELF_READ: 'orders.self.read',
    CREATE: 'orders.create',
    CREATE_LAB: 'orders.create_lab',
    CREATE_IMAGING: 'orders.create_imaging',
    CREATE_PROCEDURE: 'orders.create_procedure',
    CREATE_MEDICATION: 'orders.create_medication',
    CREATE_SERVICE: 'orders.create_service',
    UPDATE: 'orders.update',
    ACKNOWLEDGE: 'orders.acknowledge',
    START: 'orders.start',
    COMPLETE: 'orders.complete',
    CANCEL: 'orders.cancel',
    CANCEL_OWN: 'orders.cancel_own',
    CANCEL_DEPARTMENT: 'orders.cancel_department',
    ENTERED_IN_ERROR: 'orders.entered_in_error',
    DISPATCH: 'orders.dispatch',
    CREATE_CHARGE: 'orders.create_charge',
    SUMMARY_READ: 'orders.summary.read',
    TIMELINE_READ: 'orders.timeline.read',
    OVERRIDE_CANCEL_IN_PROGRESS: 'orders.override_cancel_in_progress',
    OVERRIDE_SAFETY_WARNING: 'orders.override_safety_warning',
  },
  LAB_ORDERS: {
    READ: 'lab_orders.read',
    READ_OWN: 'lab_orders.read_own',
    READ_DEPARTMENT: 'lab_orders.read_department',
    ACKNOWLEDGE: 'lab_orders.acknowledge',
    CANCEL: 'lab_orders.cancel',
    COLLECT: 'lab_orders.collect',
    PROCESS: 'lab_orders.process',
    UPDATE_STATUS: 'lab_orders.update_status',
  },
  SPECIMENS: {
    READ: 'specimens.read',
    CREATE: 'specimens.create',
    COLLECT: 'specimens.collect',
    RECEIVE: 'specimens.receive',
    REJECT: 'specimens.reject',
    PROCESS: 'specimens.process',
    STORE: 'specimens.store',
    DISPOSE: 'specimens.dispose',
    DISCARD: 'specimens.discard',
  },
  LAB_RESULTS: {
    READ: 'lab_results.read',
    READ_FINAL: 'lab_results.read_final',
    SELF_READ_RELEASED: 'lab_results.self.read_released',
    CREATE: 'lab_results.create',
    UPDATE_OWN: 'lab_results.update_own',
    WRITE: 'lab_results.write',
    FINALIZE: 'lab_results.finalize',
    AMEND: 'lab_results.amend',
    CRITICAL_ACKNOWLEDGE: 'lab_results.critical_acknowledge',
    CANCEL: 'lab_results.cancel',
    ENTERED_IN_ERROR: 'lab_results.entered_in_error',
    RELEASE_TO_PATIENT: 'lab_results.release_to_patient',
  },
  LAB_RESULT_ITEMS: {
    CREATE: 'lab_result_items.create',
    UPDATE: 'lab_result_items.update',
    DELETE: 'lab_result_items.delete',
  },
  IMAGING_ORDERS: {
    READ: 'imaging_orders.read',
    READ_OWN: 'imaging_orders.read_own',
    READ_DEPARTMENT: 'imaging_orders.read_department',
    START: 'imaging_orders.start',
    COMPLETE: 'imaging_orders.complete',
    UPDATE_STATUS: 'imaging_orders.update_status',
    CANCEL_BY_POLICY: 'imaging_orders.cancel_by_policy',
  },
  IMAGING_REPORTS: {
    READ: 'imaging_reports.read',
    READ_FINAL: 'imaging_reports.read_final',
    SELF_READ_RELEASED: 'imaging_reports.self.read_released',
    CREATE: 'imaging_reports.create',
    UPDATE_OWN: 'imaging_reports.update_own',
    WRITE: 'imaging_reports.write',
    FINALIZE: 'imaging_reports.finalize',
    AMEND: 'imaging_reports.amend',
    CANCEL: 'imaging_reports.cancel',
    RELEASE_TO_PATIENT: 'imaging_reports.release_to_patient',
    CRITICAL_ACKNOWLEDGE: 'imaging_reports.critical_acknowledge',
  },
  PROCEDURE_ORDERS: {
    READ: 'procedure_orders.read',
    READ_OWN: 'procedure_orders.read_own',
    READ_DEPARTMENT: 'procedure_orders.read_department',
    SELF_READ_COMPLETED: 'procedure_orders.self.read_completed',
    SCHEDULE: 'procedure_orders.schedule',
    START: 'procedure_orders.start',
    UPDATE: 'procedure_orders.update',
    COMPLETE: 'procedure_orders.complete',
    CANCEL: 'procedure_orders.cancel',
    NO_SHOW: 'procedure_orders.no_show',
    CHARGE_CREATE: 'procedure_orders.charge.create',
    SUMMARY_READ: 'procedure_orders.summary.read',
  },
  DIAGNOSTIC_ALERTS: {
    READ: 'diagnostic_alerts.read',
    READ_OWN: 'diagnostic_alerts.read_own',
    READ_DEPARTMENT: 'diagnostic_alerts.read_department',
    READ_ASSIGNED: 'diagnostic_alerts.read_assigned',
    ACKNOWLEDGE: 'diagnostic_alerts.acknowledge',
    ASSIGN: 'diagnostic_alerts.assign',
    ESCALATE: 'diagnostic_alerts.escalate',
    RESOLVE: 'diagnostic_alerts.resolve',
    DISMISS: 'diagnostic_alerts.dismiss',
    BULK_ACTION: 'diagnostic_alerts.bulk_action',
    MANAGE: 'diagnostic_alerts.manage',
  },
  LAB_TEST_CATALOG: {
    READ: 'lab_test_catalog.read',
    CREATE: 'lab_test_catalog.create',
    UPDATE: 'lab_test_catalog.update',
    RETIRE: 'lab_test_catalog.retire',
    IMPORT: 'lab_test_catalog.import',
    EXPORT: 'lab_test_catalog.export',
    APPROVE: 'lab_test_catalog.approve',
  },
  SPECIMEN_TYPE_CATALOG: {
    READ: 'specimen_type_catalog.read',
    CREATE: 'specimen_type_catalog.create',
    UPDATE: 'specimen_type_catalog.update',
    RETIRE: 'specimen_type_catalog.retire',
  },
  IMAGING_MODALITY_CATALOG: {
    READ: 'imaging_modality_catalog.read',
    CREATE: 'imaging_modality_catalog.create',
    UPDATE: 'imaging_modality_catalog.update',
    RETIRE: 'imaging_modality_catalog.retire',
  },
  IMAGING_EQUIPMENT: {
    READ: 'imaging_equipment.read',
    CREATE: 'imaging_equipment.create',
    UPDATE: 'imaging_equipment.update',
    MAINTENANCE: 'imaging_equipment.maintenance',
    DISABLE: 'imaging_equipment.disable',
  },
  PROCEDURE_CATALOG: {
    READ: 'procedure_catalog.read',
    CREATE: 'procedure_catalog.create',
    UPDATE: 'procedure_catalog.update',
    RETIRE: 'procedure_catalog.retire',
  },
  CLINICAL_SLA_RULES: {
    READ: 'clinical_sla_rules.read',
    CREATE: 'clinical_sla_rules.create',
    UPDATE: 'clinical_sla_rules.update',
    ACTIVATE: 'clinical_sla_rules.activate',
    DEACTIVATE: 'clinical_sla_rules.deactivate',
  },
  RESULT_REPORT_TEMPLATES: {
    READ: 'result_report_templates.read',
    CREATE: 'result_report_templates.create',
    UPDATE: 'result_report_templates.update',
    PUBLISH: 'result_report_templates.publish',
    RETIRE: 'result_report_templates.retire',
  },
  MEDICATIONS: {
    READ: 'medications.read',
    CREATE: 'medications.create',
    UPDATE: 'medications.update',
    RETIRE: 'medications.retire',
    DELETE: 'medications.delete',
    MANAGE: 'medications.manage',
  },
  PRESCRIPTIONS: {
    READ: 'prescriptions.read',
    READ_OWN: 'prescriptions.read_own',
    READ_DEPARTMENT: 'prescriptions.read_department',
    SELF_READ: 'prescriptions.self.read',
    CREATE: 'prescriptions.create',
    UPDATE_OWN: 'prescriptions.update_own',
    VERIFY: 'prescriptions.verify',
    REJECT: 'prescriptions.reject',
    CANCEL: 'prescriptions.cancel',
    CANCEL_OWN: 'prescriptions.cancel_own',
    CANCEL_BY_POLICY: 'prescriptions.cancel_by_policy',
  },
  DISPENSES: {
    READ: 'dispenses.read',
    CREATE: 'dispenses.create',
    UPDATE: 'dispenses.update',
    COMPLETE: 'dispenses.complete',
    CANCEL: 'dispenses.cancel',
    RETURN: 'dispenses.return',
  },
  MEDICATION_ADMINISTRATIONS: {
    READ: 'medication_administrations.read',
    ADMINISTER: 'medication_administrations.administer',
    HOLD: 'medication_administrations.hold',
    REFUSE: 'medication_administrations.refuse',
    OMIT: 'medication_administrations.omit',
  },
  WARD_BOARD: {
    READ: 'ward_board.read',
  },
  BED_SUGGESTIONS: {
    READ: 'bed_suggestions.read',
    CREATE: 'bed_suggestions.create',
  },
  DISCHARGE_READINESS: {
    READ: 'discharge_readiness.read',
  },
  INPATIENT_TASKS: {
    READ: 'inpatient_tasks.read',
    READ_DEPARTMENT: 'inpatient_tasks.read_department',
    CREATE: 'inpatient_tasks.create',
    UPDATE: 'inpatient_tasks.update',
    ASSIGN: 'inpatient_tasks.assign',
    START: 'inpatient_tasks.start',
    COMPLETE: 'inpatient_tasks.complete',
    CANCEL: 'inpatient_tasks.cancel',
    MANAGE: 'inpatient_tasks.manage',
  },
  INPATIENT_HANDOVERS: {
    READ: 'inpatient_handovers.read',
    READ_DEPARTMENT: 'inpatient_handovers.read_department',
    CREATE: 'inpatient_handovers.create',
    UPDATE: 'inpatient_handovers.update',
    SIGN: 'inpatient_handovers.sign',
    ACKNOWLEDGE: 'inpatient_handovers.acknowledge',
    CLOSE: 'inpatient_handovers.close',
    REOPEN: 'inpatient_handovers.reopen',
    MANAGE: 'inpatient_handovers.manage',
  },
  STOCK_BATCHES: {
    READ: 'stock_batches.read',
    CREATE: 'stock_batches.create',
    UPDATE: 'stock_batches.update',
    SELECT_FOR_DISPENSE: 'stock_batches.select_for_dispense',
    QUARANTINE: 'stock_batches.quarantine',
    RECALL: 'stock_batches.recall',
    MARK_EXPIRED: 'stock_batches.mark_expired',
    DEACTIVATE: 'stock_batches.deactivate',
  },
  INVENTORY_TRANSACTIONS: {
    READ: 'inventory_transactions.read',
    READ_RELATED: 'inventory_transactions.read_related',
    CREATE_RECEIPT: 'inventory_transactions.create_receipt',
    CREATE_ISSUE: 'inventory_transactions.create_issue',
    CREATE_RETURN_IN: 'inventory_transactions.create_return_in',
    CREATE_ADJUSTMENT_IN: 'inventory_transactions.create_adjustment_in',
    CREATE_ADJUSTMENT_OUT: 'inventory_transactions.create_adjustment_out',
    CREATE_TRANSFER_IN: 'inventory_transactions.create_transfer_in',
    CREATE_TRANSFER_OUT: 'inventory_transactions.create_transfer_out',
    CREATE_DISPOSAL: 'inventory_transactions.create_disposal',
    EXPORT: 'inventory_transactions.export',
  },
  ROOMS: {
    READ: 'rooms.read',
    READ_DEPARTMENT: 'rooms.read_department',
    CREATE: 'rooms.create',
    UPDATE: 'rooms.update',
    DELETE: 'rooms.delete',
    MANAGE: 'rooms.manage',
  },
  BEDS: {
    READ: 'beds.read',
    READ_DEPARTMENT: 'beds.read_department',
    CREATE: 'beds.create',
    UPDATE: 'beds.update',
    DELETE: 'beds.delete',
    AVAILABLE_READ: 'beds.available.read',
    AVAILABLE_READ_DEPARTMENT: 'beds.available.read_department',
    STATUS_UPDATE: 'beds.status.update',
    MANAGE: 'beds.manage',
  },
  ADMISSIONS: {
    READ: 'admissions.read',
    SELF_READ: 'admissions.self.read',
    READ_OWN: 'admissions.read_own',
    READ_DEPARTMENT: 'admissions.read_department',
    CREATE: 'admissions.create',
    CREATE_OWN: 'admissions.create_own',
    ADMIT: 'admissions.admit',
    UPDATE: 'admissions.update',
    TRANSFER: 'admissions.transfer',
    DISCHARGE: 'admissions.discharge',
    DISCHARGE_OWN: 'admissions.discharge_own',
    CANCEL: 'admissions.cancel',
  },
  BED_ASSIGNMENTS: {
    READ: 'bed_assignments.read',
    READ_DEPARTMENT: 'bed_assignments.read_department',
    CREATE: 'bed_assignments.create',
    RELEASE: 'bed_assignments.release',
    TRANSFER: 'bed_assignments.transfer',
    CANCEL: 'bed_assignments.cancel',
  },
  INPATIENT_CHARGES: {
    READ: 'inpatient_charges.read',
    CREATE: 'inpatient_charges.create',
  },
  SERVICE_CATALOG: {
    READ: 'service_catalog.read',
    CREATE: 'service_catalog.create',
    UPDATE: 'service_catalog.update',
    DELETE: 'service_catalog.delete',
    BULK_UPDATE: 'service_catalog.bulk_update',
    IMPORT: 'service_catalog.import',
    EXPORT: 'service_catalog.export',
    REACTIVATE: 'service_catalog.reactivate',
    APPROVE_PRICE_CHANGE: 'service_catalog.approve_price_change',
    READ_AUDIT: 'service_catalog.read_audit',
  },
  CHARGES: {
    READ: 'charges.read',
    CREATE: 'charges.create',
    UPDATE: 'charges.update',
    POST: 'charges.post',
    ADJUST: 'charges.adjust',
    VOID: 'charges.void',
    REQUEST_CREATE: 'charges.request_create',
    REQUEST_CREATE_MEDICATION: 'charges.request_create_medication',
    MANAGE: 'charges.manage',
  },
  INVOICES: {
    READ: 'invoices.read',
    SELF_READ: 'invoices.self.read',
    CREATE: 'invoices.create',
    UPDATE: 'invoices.update',
    ISSUE: 'invoices.issue',
    VOID: 'invoices.void',
    VOID_BY_POLICY: 'invoices.void_by_policy',
    CANCEL: 'invoices.cancel',
    PRINT: 'invoices.print',
    READ_UNPAID: 'invoices.read_unpaid',
  },
  PAYMENTS: {
    READ: 'payments.read',
    SELF_READ: 'payments.self.read',
    CREATE: 'payments.create',
    SELF_CREATE_ONLINE: 'payments.self.create_online',
    CANCEL_PENDING: 'payments.cancel_pending',
    PRINT_RECEIPT: 'payments.print_receipt',
    REFUND: 'payments.refund',
    REVERSE: 'payments.reverse',
    REFUND_REQUEST: 'payments.refund_request',
  },
  PAYMENT_INTENTS: {
    SELF_CREATE: 'payment_intents.self.create',
    SELF_READ: 'payment_intents.self.read',
    READ: 'payment_intents.read',
    CANCEL: 'payment_intents.cancel',
  },
  PAYMENT_RECONCILIATION: {
    READ: 'payment_reconciliation.read',
    IMPORT: 'payment_reconciliation.import',
    MATCH: 'payment_reconciliation.match',
    AUTO_MATCH: 'payment_reconciliation.auto_match',
    UNMATCH: 'payment_reconciliation.unmatch',
    APPROVE: 'payment_reconciliation.approve',
    REJECT: 'payment_reconciliation.reject',
    LOCK_PERIOD: 'payment_reconciliation.lock_period',
    EXPORT: 'payment_reconciliation.export',
    MANAGE_RULES: 'payment_reconciliation.manage_rules',
  },
  RECEIPTS: {
    READ: 'receipts.read',
    SELF_READ: 'receipts.self.read',
    GENERATE: 'receipts.generate',
    PRINT: 'receipts.print',
    REPRINT: 'receipts.reprint',
    DOWNLOAD: 'receipts.download',
    SELF_DOWNLOAD: 'receipts.self.download',
    SEND: 'receipts.send',
    EXPORT: 'receipts.export',
    VOID: 'receipts.void',
    VIEW_AUDIT: 'receipts.view_audit',
    APPROVE_REPRINT: 'receipts.approve_reprint',
  },
  INSURANCE_POLICIES: {
    READ: 'insurance_policies.read',
    SELF_READ: 'insurance_policies.self.read',
    CREATE: 'insurance_policies.create',
    CREATE_BASIC: 'insurance_policies.create_basic',
    UPDATE: 'insurance_policies.update',
    DEACTIVATE: 'insurance_policies.deactivate',
    SELF_SUBMIT_INFO: 'insurance_policies.self.submit_info',
    VERIFY: 'insurance_policies.verify',
    REJECT: 'insurance_policies.reject',
  },
  INSURANCE_CLAIMS: {
    READ: 'insurance_claims.read',
    SELF_READ: 'insurance_claims.self.read',
    CREATE: 'insurance_claims.create',
    UPDATE: 'insurance_claims.update',
    SUBMIT: 'insurance_claims.submit',
    MARK_UNDER_REVIEW: 'insurance_claims.mark_under_review',
    APPROVE: 'insurance_claims.approve',
    PARTIALLY_APPROVE: 'insurance_claims.partially_approve',
    REJECT: 'insurance_claims.reject',
    SETTLE: 'insurance_claims.settle',
    CANCEL: 'insurance_claims.cancel',
    MANAGE: 'insurance_claims.manage',
  },
  MEDICAL_RECORDS: {
    READ: 'medical_records.read',
    READ_OWN: 'medical_records.read_own',
    READ_DEPARTMENT: 'medical_records.read_department',
    READ_ASSIGNED: 'medical_records.read_assigned',
    SELF_READ_RELEASED: 'medical_records.self.read_released',
    RELATIVE_READ_RELEASED_IF_AUTHORIZED: 'medical_records.relative.read_released_if_authorized',
    CREATE: 'medical_records.create',
    CREATE_SUMMARY: 'medical_records.create_summary',
    UPDATE: 'medical_records.update',
    FINALIZE: 'medical_records.finalize',
    FINALIZE_OWN: 'medical_records.finalize_own',
    FINALIZE_BY_POLICY: 'medical_records.finalize_by_policy',
    SEAL: 'medical_records.seal',
    AMEND: 'medical_records.amend',
    AMEND_BY_POLICY: 'medical_records.amend_by_policy',
    ARCHIVE: 'medical_records.archive',
    VOID: 'medical_records.void',
    EXPORT: 'medical_records.export',
    RELEASE_TO_PATIENT: 'medical_records.release_to_patient',
  },
  ATTACHMENTS: {
    READ: 'attachments.read',
    READ_OWN: 'attachments.read_own',
    READ_DEPARTMENT: 'attachments.read_department',
    READ_BY_ENTITY: 'attachments.read_by_entity',
    READ_CLINICAL: 'attachments.read_clinical',
    READ_LAB: 'attachments.read_lab',
    READ_IMAGING: 'attachments.read_imaging',
    READ_PROCEDURE: 'attachments.read_procedure',
    READ_INSURANCE: 'attachments.read_insurance',
    SELF_READ: 'attachments.self.read',
    SELF_READ_RELEASED: 'attachments.self.read_released',
    SELF_DOWNLOAD_RELEASED: 'attachments.self.download_released',
    CREATE: 'attachments.create',
    UPLOAD: 'attachments.upload',
    UPLOAD_CLINICAL: 'attachments.upload_clinical',
    UPLOAD_LAB: 'attachments.upload_lab',
    UPLOAD_IMAGING: 'attachments.upload_imaging',
    UPLOAD_IMAGING_REPORT: 'attachments.upload_imaging_report',
    UPLOAD_PROCEDURE: 'attachments.upload_procedure',
    UPLOAD_INSURANCE: 'attachments.upload_insurance',
    SELF_UPLOAD_BASIC: 'attachments.self.upload_basic',
    ARCHIVE: 'attachments.archive',
    DELETE_SOFT: 'attachments.delete_soft',
    RESTORE: 'attachments.restore',
    DOWNLOAD: 'attachments.download',
    RELEASE_TO_PATIENT: 'attachments.release_to_patient',
    MANAGE: 'attachments.manage',
  },
  DOCUMENTS: {
    TIMELINE_READ: 'documents.timeline.read',
    TIMELINE_READ_OWN: 'documents.timeline.read_own',
    TIMELINE_READ_DEPARTMENT: 'documents.timeline.read_department',
    SELF_UPLOAD: 'documents.self.upload',
    SELF_ARCHIVE: 'documents.self.archive',
    SELF_EXPORT_ZIP: 'documents.self.export_zip',
    REVIEW: 'documents.review',
    APPROVE: 'documents.approve',
    REJECT: 'documents.reject',
  },
  QR_TOKENS: {
    CREATE: 'qr_tokens.create',
    VERIFY: 'qr_tokens.verify',
    REVOKE: 'qr_tokens.revoke',
  },
  NOTIFICATIONS: {
    READ: 'notifications.read',
    READ_OWN: 'notifications.read_own',
    CREATE: 'notifications.create',
    CREATE_SYSTEM: 'notifications.create_system',
    CREATE_INTERNAL: 'notifications.create_internal',
    BROADCAST: 'notifications.broadcast',
    MARK_READ: 'notifications.mark_read',
    MARK_ALL_READ: 'notifications.mark_all_read',
    CANCEL: 'notifications.cancel',
    RETRY: 'notifications.retry',
    DISPATCH: 'notifications.dispatch',
    MANAGE: 'notifications.manage',
    READ_FAILED: 'notifications.read_failed',
    SELF_READ: 'notifications.self.read',
    SELF_MARK_READ: 'notifications.self.mark_read',
    SELF_MARK_ALL_READ: 'notifications.self.mark_all_read',
    RELATIVE_READ: 'notifications.relative.read',
  },
  MESSAGES: {
    SELF_READ: 'messages.self.read',
    SELF_SEND: 'messages.self.send',
    STAFF_READ: 'messages.staff.read',
    STAFF_SEND: 'messages.staff.send',
    INTERNAL_READ: 'messages.internal.read',
    INTERNAL_SEND: 'messages.internal.send',
    ASSIGN: 'messages.assign',
    CLOSE: 'messages.close',
    EXPORT: 'messages.export',
    MANAGE: 'messages.manage',
  },
  SUPPORT_TICKETS: {
    SELF_CREATE: 'support_tickets.self.create',
    SELF_READ: 'support_tickets.self.read',
    REPLY: 'support_tickets.reply',
    ASSIGN: 'support_tickets.assign',
    RESOLVE: 'support_tickets.resolve',
    MANAGE: 'support_tickets.manage',
  },
  EMERGENCY: {
    SELF_SOS: 'emergency.self.sos',
    READ: 'emergency.read',
    ACKNOWLEDGE: 'emergency.acknowledge',
    TRIAGE: 'emergency.triage',
    RESOLVE: 'emergency.resolve',
  },
  CONSENTS: {
    SELF_READ: 'consents.self.read',
    SELF_SIGN: 'consents.self.sign',
    MANAGE: 'consents.manage',
  },
  BREAK_GLASS: {
    START: 'break_glass.start',
    READ: 'break_glass.read',
  },
  DIRECTORY: {
    READ: 'directory.read',
    MANAGE: 'directory.manage',
  },
  AUDIT_LOGS: {
    READ: 'audit_logs.read',
    READ_LIMITED: 'audit_logs.read_limited',
    READ_ACTOR: 'audit_logs.read_actor',
    READ_ENTITY: 'audit_logs.read_entity',
    READ_SECURITY: 'audit_logs.read_security',
    READ_SCHEDULE: 'audit_logs.read_schedule',
    EXPORT: 'audit_logs.export',
  },
  REPORTS: {
    READ: 'reports.read',
    READ_ALL: 'reports.read_all',
    EXPORT: 'reports.export',
    ADMIN_DASHBOARD_READ: 'reports.admin_dashboard.read',
    APPOINTMENTS_READ: 'reports.appointments.read',
    ENCOUNTERS_READ: 'reports.encounters.read',
    REVENUE_READ: 'reports.revenue.read',
    DEPARTMENT_PERFORMANCE_READ: 'reports.department_performance.read',
    DOCTOR_PERFORMANCE_READ: 'reports.doctor_performance.read',
    QUEUE_READ: 'reports.queue.read',
    INVENTORY_READ: 'reports.inventory.read',
    EXPIRING_STOCK_READ: 'reports.expiring_stock.read',
    LOW_STOCK_READ: 'reports.low_stock.read',
    BED_UTILIZATION_READ: 'reports.bed_utilization.read',
    BILLING_READ: 'reports.billing.read',
    BILLING_EXPORT: 'reports.billing.export',
    INSURANCE_READ: 'reports.insurance.read',
    INSURANCE_EXPORT: 'reports.insurance.export',
    MEDICAL_RECORDS_READ: 'reports.medical_records.read',
    MEDICAL_RECORDS_EXPORT: 'reports.medical_records.export',
  },
  PHARMACY_REPORTS: {
    DASHBOARD_READ: 'pharmacy_reports.dashboard.read',
    INVENTORY_OVERVIEW_READ: 'pharmacy_reports.inventory_overview.read',
    INVENTORY_MOVEMENT_READ: 'pharmacy_reports.inventory_movement.read',
    DISPENSING_READ: 'pharmacy_reports.dispensing.read',
    EXPIRING_STOCK_READ: 'pharmacy_reports.expiring_stock.read',
    LOW_STOCK_READ: 'pharmacy_reports.low_stock.read',
    INVENTORY_VALUATION_READ: 'pharmacy_reports.inventory_valuation.read',
    HIGH_USAGE_READ: 'pharmacy_reports.high_usage.read',
    WASTE_DISPOSAL_READ: 'pharmacy_reports.waste_disposal.read',
    EXPORT: 'pharmacy_reports.export',
  },
  PHARMACY_CONFIG: {
    READ: 'pharmacy_config.read',
    CREATE: 'pharmacy_config.create',
    UPDATE: 'pharmacy_config.update',
    DELETE: 'pharmacy_config.delete',
    MERGE: 'pharmacy_config.merge',
    IMPORT: 'pharmacy_config.import',
    EXPORT: 'pharmacy_config.export',
  },
  PHARMACY_POLICY: {
    READ: 'pharmacy_policy.read',
    CREATE: 'pharmacy_policy.create',
    UPDATE: 'pharmacy_policy.update',
    ACTIVATE: 'pharmacy_policy.activate',
    DEACTIVATE: 'pharmacy_policy.deactivate',
    TEST: 'pharmacy_policy.test',
  },
  CONTROLLED_DRUG_POLICY: {
    READ: 'controlled_drug_policy.read',
    MANAGE: 'controlled_drug_policy.manage',
  },
  CONTROLLED_DRUG_LEDGER: {
    READ: 'controlled_drug_ledger.read',
    CREATE: 'controlled_drug_ledger.create',
  },
};

const LEGACY_PERMISSION = {
  AUTH_STAFF_CREATE: 'auth.staff.create',
  AUTH_STAFF_MANAGE_ROLES: 'auth.staff.manage_roles',
  AUTH_STAFF_READ: 'auth.staff.read',
  AUTH_STAFF_UPDATE_STATUS: 'auth.staff.update_status',
  AUTH_STAFF_RESET_PASSWORD: 'auth.staff.reset_password',
  AUTH_STAFF_PERMISSIONS_READ: 'auth.staff.permissions.read',
  AUTH_STAFF_ROLES_READ: 'auth.staff.roles.read',
  AUTH_AUDIT_READ: 'auth.audit.read',
  ROLE_READ: 'role.read',
  ROLE_USERS_READ: 'role.users.read',
  ROLE_CREATE: 'role.create',
  ROLE_UPDATE: 'role.update',
  ROLE_UPDATE_STATUS: 'role.update_status',
  ROLE_ASSIGN_PERMISSIONS: 'role.assign_permissions',
  PERMISSION_READ: 'permission.read',
  PERMISSION_CREATE: 'permission.create',
  PERMISSION_UPDATE: 'permission.update',
  DEPARTMENT_READ: 'department.read',
  DEPARTMENT_WRITE: 'department.write',
  SCHEDULE_READ: 'schedule.read',
  SCHEDULE_WRITE: 'schedule.write',
  SCHEDULE_PUBLISH: 'schedule.publish',
  SCHEDULE_CANCEL: 'schedule.cancel',
  PATIENTS_SELF_READ: 'patients.self.read',
  PATIENTS_SELF_UPDATE: 'patients.self.update',
  APPOINTMENTS_SELF_READ: 'appointments.self.read',
  APPOINTMENTS_SELF_CREATE: 'appointments.self.create',
  PATIENTS_READ: 'patients.read',
  PATIENTS_WRITE: 'patients.write',
  APPOINTMENTS_READ: 'appointments.read',
  APPOINTMENTS_WRITE: 'appointments.write',
  QUEUE_MANAGE: 'queue.manage',
  ENCOUNTERS_READ: 'encounters.read',
  ENCOUNTERS_WRITE: 'encounters.write',
  CONSULTATIONS_WRITE: 'consultations.write',
  DIAGNOSES_WRITE: 'diagnoses.write',
  VITALS_WRITE: 'vitals.write',
  MEDICATIONS_READ: 'medications.read',
  PRESCRIPTIONS_WRITE: 'prescriptions.write',
};

const RAW_LEGACY_PERMISSION_CODES = Object.values(LEGACY_PERMISSION);

const PERMISSION_ALIASES = {
  [LEGACY_PERMISSION.AUTH_STAFF_CREATE]: PERMISSION.USERS.CREATE,
  [LEGACY_PERMISSION.AUTH_STAFF_MANAGE_ROLES]: PERMISSION.USERS.ASSIGN_ROLES,
  [LEGACY_PERMISSION.AUTH_STAFF_READ]: PERMISSION.USERS.READ,
  [LEGACY_PERMISSION.AUTH_STAFF_UPDATE_STATUS]: PERMISSION.USERS.UPDATE,
  [LEGACY_PERMISSION.AUTH_STAFF_RESET_PASSWORD]: PERMISSION.USERS.RESET_PASSWORD,
  [LEGACY_PERMISSION.AUTH_STAFF_PERMISSIONS_READ]: PERMISSION.PERMISSIONS.READ,
  [LEGACY_PERMISSION.AUTH_STAFF_ROLES_READ]: PERMISSION.ROLES.READ,
  [LEGACY_PERMISSION.AUTH_AUDIT_READ]: PERMISSION.AUDIT_LOGS.READ,
  [LEGACY_PERMISSION.ROLE_READ]: PERMISSION.ROLES.READ,
  [LEGACY_PERMISSION.ROLE_USERS_READ]: PERMISSION.USERS.READ,
  [LEGACY_PERMISSION.ROLE_CREATE]: PERMISSION.ROLES.CREATE,
  [LEGACY_PERMISSION.ROLE_UPDATE]: PERMISSION.ROLES.UPDATE,
  [LEGACY_PERMISSION.ROLE_UPDATE_STATUS]: PERMISSION.ROLES.UPDATE,
  [LEGACY_PERMISSION.ROLE_ASSIGN_PERMISSIONS]: PERMISSION.ROLES.ASSIGN_PERMISSIONS,
  [LEGACY_PERMISSION.PERMISSION_READ]: PERMISSION.PERMISSIONS.READ,
  [LEGACY_PERMISSION.PERMISSION_CREATE]: PERMISSION.PERMISSIONS.CREATE,
  [LEGACY_PERMISSION.PERMISSION_UPDATE]: PERMISSION.PERMISSIONS.UPDATE,
  [LEGACY_PERMISSION.DEPARTMENT_READ]: PERMISSION.DEPARTMENTS.READ,
  [LEGACY_PERMISSION.DEPARTMENT_WRITE]: PERMISSION.DEPARTMENTS.UPDATE,
  [LEGACY_PERMISSION.SCHEDULE_READ]: PERMISSION.SCHEDULES.READ,
  [LEGACY_PERMISSION.SCHEDULE_WRITE]: PERMISSION.SCHEDULES.UPDATE,
  [LEGACY_PERMISSION.SCHEDULE_PUBLISH]: PERMISSION.SCHEDULES.PUBLISH,
  [LEGACY_PERMISSION.SCHEDULE_CANCEL]: PERMISSION.SCHEDULES.CANCEL,
  [LEGACY_PERMISSION.PATIENTS_SELF_READ]: PERMISSION.PATIENTS.SELF_READ,
  [LEGACY_PERMISSION.PATIENTS_SELF_UPDATE]: PERMISSION.PATIENTS.SELF_UPDATE_BASIC,
  [LEGACY_PERMISSION.APPOINTMENTS_SELF_READ]: PERMISSION.APPOINTMENTS.SELF_READ,
  [LEGACY_PERMISSION.APPOINTMENTS_SELF_CREATE]: PERMISSION.APPOINTMENTS.SELF_CREATE,
  [LEGACY_PERMISSION.PATIENTS_READ]: PERMISSION.PATIENTS.READ,
  [LEGACY_PERMISSION.PATIENTS_WRITE]: PERMISSION.PATIENTS.UPDATE,
  [LEGACY_PERMISSION.APPOINTMENTS_READ]: PERMISSION.APPOINTMENTS.READ,
  [LEGACY_PERMISSION.APPOINTMENTS_WRITE]: PERMISSION.APPOINTMENTS.UPDATE,
  [LEGACY_PERMISSION.QUEUE_MANAGE]: PERMISSION.QUEUE.UPDATE,
  [LEGACY_PERMISSION.ENCOUNTERS_READ]: PERMISSION.ENCOUNTERS.READ,
  [LEGACY_PERMISSION.ENCOUNTERS_WRITE]: PERMISSION.ENCOUNTERS.UPDATE,
  [LEGACY_PERMISSION.CONSULTATIONS_WRITE]: PERMISSION.CONSULTATIONS.UPDATE,
  [LEGACY_PERMISSION.DIAGNOSES_WRITE]: PERMISSION.DIAGNOSES.UPDATE,
  [LEGACY_PERMISSION.VITALS_WRITE]: PERMISSION.VITAL_SIGNS.CREATE,
  [LEGACY_PERMISSION.MEDICATIONS_READ]: PERMISSION.MEDICATIONS.READ,
  [LEGACY_PERMISSION.PRESCRIPTIONS_WRITE]: PERMISSION.PRESCRIPTIONS.CREATE,
};

function flattenPermissions(permissionObject = PERMISSION) {
  return Object.values(permissionObject).flatMap((group) => Object.values(group));
}

const CANONICAL_PERMISSION_CODES = [...new Set(flattenPermissions())];
const PERMISSION_CODES = CANONICAL_PERMISSION_CODES;
const LEGACY_PERMISSION_CODES = RAW_LEGACY_PERMISSION_CODES.filter(
  (code) => !CANONICAL_PERMISSION_CODES.includes(code),
);
const ALL_SUPPORTED_PERMISSION_CODES = [
  ...new Set([...CANONICAL_PERMISSION_CODES, ...LEGACY_PERMISSION_CODES]),
];

function normalizePermissionCode(code) {
  return PERMISSION_ALIASES[code] || code;
}

function normalizePermissionCodes(codes = []) {
  return [...new Set(codes.map(normalizePermissionCode))];
}

function isLegacyPermission(code) {
  return LEGACY_PERMISSION_CODES.includes(code);
}

function formatPermissionName(code) {
  return code
    .split('.')
    .map((part) => part.replace(/_/g, ' '))
    .join(' - ');
}

function getPermissionDefinition(code) {
  const [moduleKey, ...actionParts] = String(code).split('.');
  return {
    permission_code: code,
    permission_name: formatPermissionName(code),
    module_key: moduleKey,
    action_key: actionParts.join('.'),
    is_system: true,
  };
}

module.exports = {
  PERMISSION,
  PERMISSION_CODES,
  CANONICAL_PERMISSION_CODES,
  ALL_SUPPORTED_PERMISSION_CODES,
  LEGACY_PERMISSION,
  LEGACY_PERMISSION_CODES,
  PERMISSION_ALIASES,
  flattenPermissions,
  formatPermissionName,
  getPermissionDefinition,
  normalizePermissionCode,
  normalizePermissionCodes,
  isLegacyPermission,
};
