const ROLE_CODE = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  MANAGER: 'manager',
  DEPARTMENT_HEAD: 'department_head',
  RECEPTIONIST: 'receptionist',
  SCHEDULER: 'scheduler',
  DOCTOR: 'doctor',
  NURSE: 'nurse',
  LAB_TECHNICIAN: 'lab_technician',
  LAB_MANAGER: 'lab_manager',
  RADIOLOGIST: 'radiologist',
  IMAGING_TECHNICIAN: 'imaging_technician',
  PROCEDURE_STAFF: 'procedure_staff',
  PHARMACIST: 'pharmacist',
  INVENTORY_STAFF: 'inventory_staff',
  CASHIER: 'cashier',
  BILLING_STAFF: 'billing_staff',
  INSURANCE_STAFF: 'insurance_staff',
  MEDICAL_RECORD_STAFF: 'medical_record_staff',
  PATIENT: 'patient',
  PATIENT_RELATIVE: 'patient_relative',
};

const ROLE_CODES = Object.values(ROLE_CODE);

const ROLE_PRIORITY = {
  [ROLE_CODE.SUPER_ADMIN]: 100,
  [ROLE_CODE.ADMIN]: 90,
  [ROLE_CODE.MANAGER]: 80,
  [ROLE_CODE.DEPARTMENT_HEAD]: 70,
  [ROLE_CODE.DOCTOR]: 60,
  [ROLE_CODE.RADIOLOGIST]: 60,
  [ROLE_CODE.LAB_MANAGER]: 60,
  [ROLE_CODE.MEDICAL_RECORD_STAFF]: 55,
  [ROLE_CODE.BILLING_STAFF]: 50,
  [ROLE_CODE.INSURANCE_STAFF]: 50,
  [ROLE_CODE.PHARMACIST]: 50,
  [ROLE_CODE.NURSE]: 45,
  [ROLE_CODE.SCHEDULER]: 45,
  [ROLE_CODE.RECEPTIONIST]: 40,
  [ROLE_CODE.LAB_TECHNICIAN]: 40,
  [ROLE_CODE.IMAGING_TECHNICIAN]: 40,
  [ROLE_CODE.PROCEDURE_STAFF]: 40,
  [ROLE_CODE.INVENTORY_STAFF]: 40,
  [ROLE_CODE.CASHIER]: 35,
  [ROLE_CODE.PATIENT]: 10,
  [ROLE_CODE.PATIENT_RELATIVE]: 10,
};

const CORE_ROLES = [
  { role_code: ROLE_CODE.SUPER_ADMIN, role_name: 'Super Admin' },
  { role_code: ROLE_CODE.ADMIN, role_name: 'System Admin' },
  { role_code: ROLE_CODE.MANAGER, role_name: 'Manager' },
  { role_code: ROLE_CODE.DEPARTMENT_HEAD, role_name: 'Department Head' },
  { role_code: ROLE_CODE.RECEPTIONIST, role_name: 'Receptionist' },
  { role_code: ROLE_CODE.SCHEDULER, role_name: 'Scheduler' },
  { role_code: ROLE_CODE.DOCTOR, role_name: 'Doctor' },
  { role_code: ROLE_CODE.NURSE, role_name: 'Nurse' },
  { role_code: ROLE_CODE.LAB_TECHNICIAN, role_name: 'Lab Technician' },
  { role_code: ROLE_CODE.LAB_MANAGER, role_name: 'Lab Manager' },
  { role_code: ROLE_CODE.RADIOLOGIST, role_name: 'Radiologist' },
  { role_code: ROLE_CODE.IMAGING_TECHNICIAN, role_name: 'Imaging Technician' },
  { role_code: ROLE_CODE.PROCEDURE_STAFF, role_name: 'Procedure Staff' },
  { role_code: ROLE_CODE.PHARMACIST, role_name: 'Pharmacist' },
  { role_code: ROLE_CODE.INVENTORY_STAFF, role_name: 'Inventory Staff' },
  { role_code: ROLE_CODE.CASHIER, role_name: 'Cashier' },
  { role_code: ROLE_CODE.BILLING_STAFF, role_name: 'Billing Staff' },
  { role_code: ROLE_CODE.INSURANCE_STAFF, role_name: 'Insurance Staff' },
  { role_code: ROLE_CODE.MEDICAL_RECORD_STAFF, role_name: 'Medical Record Staff' },
  { role_code: ROLE_CODE.PATIENT, role_name: 'Patient' },
  { role_code: ROLE_CODE.PATIENT_RELATIVE, role_name: 'Patient Relative' },
].map((role) => ({
  ...role,
  is_system: true,
  priority_level: ROLE_PRIORITY[role.role_code] || 0,
}));

module.exports = {
  ROLE_CODE,
  ROLE_CODES,
  ROLE_PRIORITY,
  CORE_ROLES,
};
