import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Badge,
  BadgeCheck,
  Bell,
  BellOff,
  Brain,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  ChartNoAxesCombined,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  ClipboardPenLine,
  Clock3,
  CreditCard,
  Database,
  Download,
  Droplet,
  FilePenLine,
  FileText,
  FlaskConical,
  FolderArchive,
  FolderOpen,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Image,
  Info,
  LayoutDashboard,
  ListFilter,
  LocateFixed,
  LockKeyhole,
  LogOut,
  Map,
  MapPin,
  MapPinOff,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Microscope,
  Minus,
  Moon,
  MoreVertical,
  MoveRight,
  Navigation,
  PackageCheck,
  Paperclip,
  Pencil,
  Phone,
  PhoneForwarded,
  Pill,
  Plus,
  Printer,
  ReceiptText,
  ScanLine,
  ScrollText,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  ShieldPlus,
  Siren,
  SlidersHorizontal,
  SmilePlus,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Sunset,
  Thermometer,
  Trash2,
  TrendingDown,
  TriangleAlert,
  Upload,
  UserRound,
  UserRoundCheck,
  Video,
  WalletCards,
  X,
} from 'lucide-react'

const iconComponents = {
  Activity,
  ArrowLeft,
  ArrowRight,
  Badge,
  BadgeCheck,
  Bell,
  BellOff,
  Brain,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  ChartNoAxesCombined,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleHelp,
  CirclePlus,
  ClipboardPenLine,
  Clock3,
  CreditCard,
  Database,
  Download,
  Droplet,
  FilePenLine,
  FileText,
  FlaskConical,
  FolderArchive,
  FolderOpen,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Image,
  Info,
  LayoutDashboard,
  ListFilter,
  LocateFixed,
  LockKeyhole,
  LogOut,
  Map,
  MapPin,
  MapPinOff,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Microscope,
  Minus,
  Moon,
  MoreVertical,
  MoveRight,
  Navigation,
  PackageCheck,
  Paperclip,
  Pencil,
  Phone,
  PhoneForwarded,
  Pill,
  Plus,
  Printer,
  ReceiptText,
  ScanLine,
  ScrollText,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  ShieldPlus,
  Siren,
  SlidersHorizontal,
  SmilePlus,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Sunset,
  Thermometer,
  Trash2,
  TrendingDown,
  TriangleAlert,
  Upload,
  UserRound,
  UserRoundCheck,
  Video,
  WalletCards,
  X,
}

const iconMap = {
  accessibility_new: 'UserRoundCheck',
  account_balance_wallet: 'WalletCards',
  add: 'Plus',
  add_circle: 'CirclePlus',
  analytics: 'ChartNoAxesCombined',
  apartment: 'Building2',
  arrow_back: 'ArrowLeft',
  arrow_forward: 'ArrowRight',
  attach_file: 'Paperclip',
  auto_awesome: 'Sparkles',
  badge: 'Badge',
  bedtime: 'Moon',
  biotech: 'Microscope',
  bloodtype: 'Droplet',
  calendar_add_on: 'CalendarPlus',
  calendar_month: 'CalendarDays',
  calendar_today: 'CalendarDays',
  call: 'Phone',
  campaign: 'Megaphone',
  chat: 'MessageCircle',
  check: 'Check',
  check_circle: 'CircleCheck',
  chevron_left: 'ChevronLeft',
  chevron_right: 'ChevronRight',
  clinical_notes: 'ClipboardPenLine',
  close: 'X',
  dashboard: 'LayoutDashboard',
  database: 'Database',
  delete: 'Trash2',
  dentistry: 'SmilePlus',
  description: 'FileText',
  directions: 'Navigation',
  done: 'Check',
  done_all: 'CheckCheck',
  download: 'Download',
  ecg_heart: 'HeartPulse',
  edit: 'Pencil',
  edit_note: 'FilePenLine',
  emergency: 'Siren',
  emergency_share: 'Share2',
  event: 'CalendarClock',
  expand_less: 'ChevronUp',
  expand_more: 'ChevronDown',
  experiment: 'FlaskConical',
  favorite: 'Heart',
  filter_list: 'ListFilter',
  folder_shared: 'FolderOpen',
  folder_zip: 'FolderArchive',
  forum: 'MessagesSquare',
  gastroenterology: 'Stethoscope',
  health_and_safety: 'ShieldPlus',
  help: 'CircleHelp',
  help_clinic: 'UserRound',
  help_outline: 'CircleHelp',
  history_edu: 'ScrollText',
  home: 'Home',
  image: 'Image',
  info: 'Info',
  insights: 'ChartNoAxesCombined',
  inventory_2: 'PackageCheck',
  lab_research: 'FlaskConical',
  light_mode: 'Sun',
  local_hospital: 'Hospital',
  local_pharmacy: 'Pill',
  location_off: 'MapPinOff',
  location_on: 'MapPin',
  lock: 'LockKeyhole',
  logout: 'LogOut',
  map: 'Map',
  medical_services: 'Stethoscope',
  medication: 'Pill',
  monitor_heart: 'HeartPulse',
  more_vert: 'MoreVertical',
  my_location: 'LocateFixed',
  near_me: 'Navigation',
  notifications: 'Bell',
  notifications_off: 'BellOff',
  payments: 'CreditCard',
  person: 'UserRound',
  phone_forwarded: 'PhoneForwarded',
  picture_as_pdf: 'FileText',
  pill: 'Pill',
  print: 'Printer',
  psychology: 'Brain',
  pulmonology: 'Activity',
  radiology: 'ScanLine',
  receipt_long: 'ReceiptText',
  remove: 'Minus',
  schedule: 'Clock3',
  science: 'FlaskConical',
  search: 'Search',
  security: 'ShieldCheck',
  send: 'Send',
  settings: 'Settings',
  settings_suggest: 'SlidersHorizontal',
  star: 'Star',
  thermometer: 'Thermometer',
  trending_down: 'TrendingDown',
  trending_flat: 'MoveRight',
  tune: 'SlidersHorizontal',
  upload_file: 'Upload',
  verified: 'BadgeCheck',
  verified_user: 'ShieldCheck',
  videocam: 'Video',
  warning: 'TriangleAlert',
  water_drop: 'Droplet',
  wb_sunny: 'Sun',
  wb_twilight: 'Sunset',
}

function getIconComponent(name) {
  const iconName = iconMap[name] || name
  return iconComponents[iconName] || CircleHelp
}

export default function PatientIcon({ name, className = '', ...props }) {
  const Icon = getIconComponent(name)
  const classes = ['material-symbols-outlined', 'patient-lucide-icon', className]
    .filter(Boolean)
    .join(' ')

  return <Icon className={classes} focusable="false" strokeWidth={2.25} {...props} />
}
