const coreRoles = [
  { role_code: 'super_admin', role_name: 'Super Admin' },
  { role_code: 'admin', role_name: 'System Admin' },
  { role_code: 'doctor', role_name: 'Doctor' },
  { role_code: 'receptionist', role_name: 'Receptionist' },
  { role_code: 'nurse', role_name: 'Nurse' },
  { role_code: 'pharmacist', role_name: 'Pharmacist' },
  { role_code: 'lab_technician', role_name: 'Lab Technician' },
];

const corePermissions = [
  { permission_code: 'auth.staff.create', permission_name: 'Create staff account', module_key: 'auth' },
  { permission_code: 'auth.staff.manage_roles', permission_name: 'Manage staff roles', module_key: 'auth' },
  { permission_code: 'auth.staff.read', permission_name: 'Read staff accounts', module_key: 'auth' },
  { permission_code: 'auth.staff.update_status', permission_name: 'Update staff status', module_key: 'auth' },
  { permission_code: 'auth.staff.reset_password', permission_name: 'Reset staff password', module_key: 'auth' },
  { permission_code: 'auth.staff.permissions.read', permission_name: 'Read staff permissions', module_key: 'auth' },
  { permission_code: 'auth.staff.roles.read', permission_name: 'Read staff roles', module_key: 'auth' },
  { permission_code: 'auth.audit.read', permission_name: 'Read audit logs', module_key: 'auth' },
  { permission_code: 'role.read', permission_name: 'Read roles', module_key: 'role' },
  { permission_code: 'role.users.read', permission_name: 'Read users by role', module_key: 'role' },
  { permission_code: 'role.create', permission_name: 'Create roles', module_key: 'role' },
  { permission_code: 'role.update', permission_name: 'Update roles', module_key: 'role' },
  { permission_code: 'role.update_status', permission_name: 'Update role status', module_key: 'role' },
  { permission_code: 'role.assign_permissions', permission_name: 'Assign permissions to role', module_key: 'role' },
  { permission_code: 'permission.read', permission_name: 'Read permissions', module_key: 'permission' },
  { permission_code: 'permission.create', permission_name: 'Create permissions', module_key: 'permission' },
  { permission_code: 'permission.update', permission_name: 'Update permissions', module_key: 'permission' },
  { permission_code: 'patients.self.read', permission_name: 'Patient self read', module_key: 'patients' },
  { permission_code: 'patients.self.update', permission_name: 'Patient self update', module_key: 'patients' },
  { permission_code: 'appointments.self.read', permission_name: 'Patient self read appointments', module_key: 'appointments' },
  { permission_code: 'appointments.self.create', permission_name: 'Patient self create appointments', module_key: 'appointments' },
  { permission_code: 'patients.read', permission_name: 'Read patients', module_key: 'patients' },
  { permission_code: 'patients.write', permission_name: 'Write patients', module_key: 'patients' },
  { permission_code: 'appointments.read', permission_name: 'Read appointments', module_key: 'appointments' },
  { permission_code: 'appointments.write', permission_name: 'Write appointments', module_key: 'appointments' },
  { permission_code: 'queue.manage', permission_name: 'Manage queue', module_key: 'queue' },
  { permission_code: 'encounters.read', permission_name: 'Read encounters', module_key: 'encounters' },
  { permission_code: 'encounters.write', permission_name: 'Write encounters', module_key: 'encounters' },
  { permission_code: 'consultations.write', permission_name: 'Write consultations', module_key: 'consultations' },
  { permission_code: 'diagnoses.write', permission_name: 'Write diagnoses', module_key: 'diagnoses' },
  { permission_code: 'vitals.write', permission_name: 'Write vital signs', module_key: 'vitals' },
  { permission_code: 'medications.read', permission_name: 'Read medication master', module_key: 'medications' },
  { permission_code: 'prescriptions.write', permission_name: 'Write prescriptions', module_key: 'prescriptions' },
];

const rolePermissionMap = {
  super_admin: corePermissions.map((permission) => permission.permission_code),
  admin: [
    'auth.staff.create',
    'auth.staff.manage_roles',
    'auth.staff.read',
    'auth.staff.update_status',
    'auth.staff.reset_password',
    'auth.staff.permissions.read',
    'auth.staff.roles.read',
    'auth.audit.read',
    'role.read',
    'role.users.read',
    'role.create',
    'role.update',
    'role.update_status',
    'role.assign_permissions',
    'permission.read',
    'permission.create',
    'permission.update',
    'patients.read',
    'patients.write',
    'appointments.read',
    'appointments.write',
    'queue.manage',
    'encounters.read',
    'medications.read',
  ],
  doctor: [
    'patients.read',
    'appointments.read',
    'encounters.read',
    'encounters.write',
    'consultations.write',
    'diagnoses.write',
    'prescriptions.write',
    'medications.read',
    'vitals.write',
  ],
  receptionist: [
    'patients.read',
    'patients.write',
    'appointments.read',
    'appointments.write',
    'queue.manage',
  ],
  nurse: [
    'patients.read',
    'appointments.read',
    'encounters.read',
    'vitals.write',
    'queue.manage',
  ],
  pharmacist: [
    'patients.read',
    'encounters.read',
    'medications.read',
    'prescriptions.write',
  ],
  lab_technician: [
    'patients.read',
    'encounters.read',
  ],
};

module.exports = {
  coreRoles,
  corePermissions,
  rolePermissionMap,
};
